in this we will exploraing the ev battery life bataset and checking is this have any noise or not 

so in this we will do 
- checking the columns 
- checking the rows 
- checking the missing value and also duplicate values 
- there is any miss datayped

step 1: fristly we import the required library

In [3]:
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

step 2: loading the dataset

In [4]:
df = pd.read_csv(r"D:\machine learning\machine_learning\decsion_tree_project\ev__battery_life\dataset\raw_data\ev_battery_failure_dataset.csv")
df

,vehicle_id,vehicle_brand,vehicle_model,vehicle_type,manufacturing_year,battery_manufacturer,battery_chemistry,battery_capacity_kwh,drive_type,odometer_km,vehicle_age_years,fleet_or_private,battery_serial,cycle_count,battery_health_percent,state_of_charge,depth_of_discharge,state_of_health,cell_voltage_avg,cell_voltage_std,pack_voltage,cell_temperature_avg,cell_temperature_max,internal_resistance,charge_efficiency,discharge_efficiency,remaining_capacity,capacity_loss_percent,charging_cycles_last_month,fast_charge_ratio,slow_charge_ratio,average_charge_power_kw,average_charging_time,overnight_charging_ratio,home_charging_ratio,charging_interruptions,overcharge_events,average_speed,average_trip_distance,aggressive_acceleration_score,hard_braking_score,regenerative_braking_usage,highway_driving_ratio,city_driving_ratio,daily_distance,average_ambient_temperature,maximum_temperature,minimum_temperature,humidity,altitude,terrain_type,dust_exposure,last_service_days,cooling_system_health,firmware_updates,previous_faults,maintenance_score,thermal_runaway_risk,voltage_imbalance,temperature_variance,sensor_fault_count,BMS_warning_count,abnormal_voltage_events,battery_stress_index,aging_score,thermal_health_score,charging_quality_score,driving_stress_score,predicted_remaining_life_cycles,battery_failure
0,EV100000,Nissan,Leaf,SUV,2019.0,CATL,LMO,82.54,RWD,98163.0,6.94,Private,BAT-91869505,250.0,73.61,85.23,26.34,72.93,NaN,0.01829,934.42,-15.66,-10.04,0.6585,94.63,80.08,60.76,26.39,4.0,0.206,0.797,25.46,212.2,0.543,0.675,0.0,2.0,58.0,38.7,0.0,7.0,69.4,0.352,0.676,50.6,-14.3,-5.9,-21.5,100.0,400.2,NaN,20.4,159.0,79.3,2.0,0.0,94.8,48.7,15.30,5.28,2.0,3.0,0.0,0.0,53.5,66.0,65.2,0.0,401.0,0
1,EV100001,Audi,e-tron,Sedan,2018.0,Samsung SDI,NaN,64.17,AWD,113600.0,7.79,Private,BAT-67968204,256.0,85.77,49.12,44.83,86.71,3.3658,0.01518,841.46,NaN,34.30,0.5206,95.16,94.95,55.04,14.23,3.0,0.417,0.543,55.83,68.5,NaN,0.708,0.0,2.0,30.7,29.4,36.3,33.1,80.7,0.353,0.661,50.6,26.4,44.6,18.8,72.9,702.7,Hilly,15.7,193.0,73.3,3.0,0.0,100.0,48.6,9.42,7.19,0.0,3.0,0.0,51.0,38.8,67.8,46.3,40.9,1094.0,0
2,EV100002,Toyota,bZ4X,Van,2018.0,Guoxuan,NMC,90.92,RWD,242253.0,7.85,Fleet,BAT-82263437,556.0,72.37,NaN,33.65,72.17,3.4152,NaN,853.81,16.83,31.37,0.6135,92.21,88.87,65.80,27.63,7.0,0.624,0.379,55.38,120.5,0.416,0.449,0.0,2.0,60.5,40.0,27.6,9.8,71.0,0.374,0.623,101.3,9.5,13.0,2.4,57.8,687.4,Flat,22.9,193.0,73.8,3.0,1.0,72.2,53.2,18.86,20.75,4.0,1.0,0.0,36.2,66.1,48.6,0.0,6.5,645.0,0
3,EV100003,Volkswagen,ID.3,Hatchback,2022.0,CATL,NMC,47.35,AWD,83700.0,NaN,Private,BAT-92487292,353.0,85.11,54.32,37.73,NaN,3.4202,0.01518,739.43,-1.10,6.25,0.4144,94.26,84.69,40.30,14.89,10.0,0.417,0.559,39.19,83.3,0.336,0.760,0.0,0.0,65.6,29.9,12.8,10.1,68.2,0.379,0.599,58.2,-4.2,2.0,-22.5,47.3,752.2,Hilly,59.0,60.0,88.3,0.0,0.0,95.4,53.6,12.99,9.04,0.0,3.0,1.0,23.4,32.5,58.2,NaN,NaN,867.0,0
4,EV100004,Tesla,Model X,Crossover,2015.0,BYD Battery,NMC,68.04,FWD,88784.0,11.13,Private,BAT-99314176,287.0,87.40,62.73,65.29,86.17,3.4556,0.02111,863.90,29.71,31.20,0.5663,96.60,93.78,59.47,12.60,5.0,0.250,0.755,44.07,118.2,0.454,0.586,0.0,0.0,61.6,8.1,61.0,35.4,34.2,0.000,1.000,27.5,NaN,29.8,10.3,30.6,283.6,Coastal,33.9,NaN,48.2,19.0,3.0,100.0,62.1,25.29,10.55,3.0,2.0,1.0,51.2,45.4,51.0,NaN,100.0,1090.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,EV299995,BYD,Song Plus,Hatchback,2016.0,CATL,LFP,45.99,FWD,182311.0,10.11,Private,BAT-33045539,817.0,86.91,30.51,42.42,84.85,2.8901,0.02851,692.25,34.92,43.33,0.7591,97.62,94.53,39.97,13.09,9.0,0.510,0.489,60.32,26.2,0.251,0.489,2.0,5.0,47.7,24.6,46.5,20.6,45.8,0.201,0.801,58.3,31.8,NaN,22.9,46.4,1220.6,Flat,29.7,229.0,56.0,12.0,3.0,95.2,27.6,37.31,11.36,3.0,1.0,1.0,62.3,NaN,78.6,0.0,51.5,2691.0,0
199996,EV299996,Lucid,Air,Crossover,2015.0,LG Energy Solution,NMC,67.65,AWD,275317.0,11.06,Private,BAT-45815075,840.0,65.08,77.61,30.76,65.08,3.5707,0.02711,892.68,36.04,38.57,0.7333,92.63,90.34,44.02,34.92,10.0,0.132,0.877,39.59,96.6,0.381,0.693,0.0,1.0,45.4,27.2,43.3,NaN,59.6,0.406,0.590,81.1,31.4,40.7,28.1,31.4,232.2,Hilly,19.8,173.0,61.3,14.0,2.0,100.0,64.0,24.54,7.19,2.0,5.0,2.0,33.1,89.5,59.3,73.7,57.0,420.0,0
199997,EV299997,BYD,Song Plus,SUV,NaN,BYD Battery,LFP,98.08,FWD,158747.0,4.89,Fleet,BAT-26458061,336.0,86.08,44.59,24.64,84.90,2.9875,0.01684,746.87,45.99,54.38,0.8548,93.38,93.45,84.42,13.92,7.0,0.358,0.652,NaN,137.6,0.253,0.433,NaN,0.0,47.5,87.1,27.9,7.7,62.2,0.491,0.498,109.8,41.9,58.6,34.8,27.5,646.1,Mountainous,33.3,96.0,75.1,3.0,2.0,77.2,39.4,19.93,14.79,2.0,2.0,0.0,79.0,13.1,64.7,32.8,7.6,3148.0,0
199998,EV299998,Tesla,Model Y,Hatchback,2016.0,SK On,NMC,51.49,FWD,95122.0,10.06,Private,BAT-57439589,392.0,76.61,80.70,41.93,75.50,3.5698,0.01754,839.29,30.82,37.18,0.5955,94.98,93.16,39.45,23.39,4.0,0.292,0.701,38.65,74.9,0.661,0.652,0.0,0.0,60.4,25.4,18.8,0.5,66.8,0.372,0.596,31.7,29.9,34.8,17.2,50.4,1181.9,Coastal,24.2,338.0,63.4,9.0,2.0,75.6,58.7,14.01,6.99,2.0,2.0,0.0,24.3,59.5,50.6,69.4,12.7,797.0,0
199999,EV299999,Tesla,Model 3,SUV,2024.0,CATL,NCA,88.39,RWD,54982.0,2.08,Fleet,BAT-75996204,174.0,87.31,48.64,43.10,87.80,3.3267,0.01704,831.68,33.88,40.94,0.4339,94.91,95.04,77.18,12.69,10.0,0.417,0.603,38.67,131.9,0.175,0.312,2.0,0.0,56.4,31.9,57.5,46.8,69.0,0.449,0.498,100.6,NaN,NaN,14.6,44.8,213.5,Flat,49.5,245.0,83.4,2.0,1.0,72.0,65.0,25.03,12.55,0.0,1.0,1.0,47.7,16.6,49.6,32.0,70.8,925.0,0

step 3 : stastically summery

In [5]:
df.describe()

,manufacturing_year,battery_capacity_kwh,odometer_km,vehicle_age_years,cycle_count,battery_health_percent,state_of_charge,depth_of_discharge,state_of_health,cell_voltage_avg,cell_voltage_std,pack_voltage,cell_temperature_avg,cell_temperature_max,internal_resistance,charge_efficiency,discharge_efficiency,remaining_capacity,capacity_loss_percent,charging_cycles_last_month,fast_charge_ratio,slow_charge_ratio,average_charge_power_kw,average_charging_time,overnight_charging_ratio,home_charging_ratio,charging_interruptions,overcharge_events,average_speed,average_trip_distance,aggressive_acceleration_score,hard_braking_score,regenerative_braking_usage,highway_driving_ratio,city_driving_ratio,daily_distance,average_ambient_temperature,maximum_temperature,minimum_temperature,humidity,altitude,dust_exposure,last_service_days,cooling_system_health,firmware_updates,previous_faults,maintenance_score,thermal_runaway_risk,voltage_imbalance,temperature_variance,sensor_fault_count,BMS_warning_count,abnormal_voltage_events,battery_stress_index,aging_score,thermal_health_score,charging_quality_score,driving_stress_score,predicted_remaining_life_cycles,battery_failure
count,190171.000000,193097.000000,191334.000000,192317.000000,192348.000000,191018.000000,190364.000000,191687.000000,190435.000000,190602.000000,191437.000000,193825.000000,192317.000000,190550.000000,192025.000000,190695.000000,193199.000000,193852.000000,190441.000000,192029.000000,190121.000000,190517.000000,190950.000000,193851.000000,192601.000000,190195.000000,190352.000000,192831.000000,190151.000000,192890.000000,192730.000000,190761.000000,190931.000000,193517.000000,192755.000000,191432.000000,190839.000000,191781.000000,193755.000000,191782.000000,191664.000000,193902.000000,192663.000000,190592.000000,193783.000000,193717.000000,191554.000000,192794.000000,192765.000000,193645.000000,190326.000000,190948.000000,192400.000000,192691.000000,191635.000000,193671.000000,192814.000000,193190.000000,191026.000000,200000.000000
mean,2019.501333,76.236405,102822.193327,6.495245,296.383934,87.381787,54.847079,38.290397,87.297020,3.288515,0.017473,810.927978,21.670459,29.382979,0.548260,95.054746,91.856834,67.209065,12.623381,5.354790,0.339631,0.660328,41.954183,142.147063,0.340293,0.565684,1.051767,0.606204,47.301749,24.563214,33.068344,23.806555,58.430851,0.378646,0.621208,52.770693,17.984170,27.020865,8.957200,54.988663,519.142168,36.096372,217.352631,72.214827,5.396825,1.578653,84.608303,47.341085,18.258389,11.091153,1.331032,2.024745,0.494595,35.179580,29.912538,63.538378,50.989061,40.948318,1859.485986,0.099605
std,2.873497,21.302330,87965.819977,2.878180,282.614453,12.540742,21.450372,12.754524,12.527256,0.246766,0.007938,168.692232,12.616243,14.546240,0.166226,2.381313,3.328364,22.502948,12.547661,4.176987,0.183636,0.185858,20.284613,103.529776,0.153804,0.200434,1.069231,0.809170,15.289119,18.885597,17.945183,16.123812,11.798215,0.155481,0.158019,35.315362,12.255328,12.878719,12.877922,16.883711,372.652956,20.439784,127.517089,14.119601,3.663146,1.408813,14.169773,18.532210,9.653337,4.583704,1.265969,1.579874,0.729369,21.789144,28.011328,13.764340,27.815242,29.848473,1834.356925,0.299473
min,2015.000000,25.000000,500.000000,1.370000,1.000000,21.420000,2.000000,5.000000,21.800000,2.048500,0.001000,76.752000,-20.000000,-46.998000,0.027660,80.580000,72.630000,7.560000,0.200000,1.000000,0.001000,0.000000,0.450000,8.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000,0.000000,0.000000,0.700000,0.000000,0.000000,3.000000,-25.000000,-23.300000,-42.400000,5.000000,0.000000,0.000000,24.000000,13.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000
25%,2017.000000,60.980000,36128.000000,4.000000,95.000000,80.990000,40.070000,29.600000,80.910000,3.106025,0.011700,753.920000,13.140000,20.250000,0.445400,93.740000,89.760000,50.860000,2.560000,2.000000,0.199000,0.540000,28.120000,78.600000,0.235000,0.431000,0.000000,0.000000,36.900000,10.600000,20.200000,11.200000,50.400000,0.272000,0.515000,25.300000,9.700000,18.300000,0.300000,43.500000,217.700000,21.800000,131.000000,62.000000,3.000000,0.000000,76.600000,30.700000,11.630000,7.920000,0.000000,1.000000,0.000000,19.300000,6.900000,53.900000,30.600000,15.500000,891.000000,0.000000
50%,2020.000000,75.350000,78919.000000,6.340000,218.000000,91.120000,54.940000,38.280000,91.050000,3.355800,0.016060,828.180000,21.710000,29.160000,0.540900,95.420000,92.320000,66.170000,8.890000,4.000000,0.321000,0.679000,40.170000,113.600000,0.344000,0.584000,1.000000,0.000000,47.200000,20.600000,32.700000,22.900000,58.500000,0.377000,0.623000,47.200000,18.000000,27.100000,9.000000,55.100000,453.500000,33.300000,188.000000,72.700000,5.000000,1.000000,87.200000,51.100000,16.940000,11.030000,1.000000,2.000000,0.000000,33.200000,22.600000,61.400000,53.500000,38.900000,1245.000000,0.000000
75%,2022.000000,89.990000,146010.750000,9.000000,412.000000,97.430000,69.780000,46.910000,97.330000,3.463900,0.021970,861.390000,30.280000,38.080000,0.620600,96.730000,94.370000,82.190000,19.010000,8.000000,0.459000,0.802000,53.640000,168.800000,0.448000,0.710000,2.000000,1.000000,57.700000,34.300000,45.300000,34.800000,66.400000,0.483000,0.730000,76.700000,26.400000,35.800000,17.800000,66.400000,753.100000,47.000000,271.000000,83.100000,8.000000,2.000000,96.700000,60.100000,23.510000,14.180000,2.000000,3.000000,1.000000,48.500000,45.100000,74.000000,72.800000,63.000000,3085.000000,0.000000
max,2024.000000,149.010000,450000.000000,11.550000,3369.000000,99.800000,100.000000,92.030000,100.000000,3.853000,0.059190,3883.404000,65.090000,255.444000,4.478040,99.500000,99.500000,147.310000,78.580000,41.000000,1.000000,1.000000,415.842000,600.000000,0.940000,1.000000,9.000000,7.000000,119.800000,144.100000,100.000000,100.000000,100.000000,1.000000,1.000000,205.300000,48.000000,71.400000,48.000000,100.000000,2621.300000,100.000000,1500.000000,100.000000,30.000000,11.000000,100.000000,100.000000,190.638000,32.940000,10.000000,13.000000,7.000000,100.000000,100.000000,100.000000,100.000000,100.000000,15474.000000,1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 70 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   vehicle_id                       200000 non-null  object
 1   vehicle_brand                    193564 non-null  object
 2   vehicle_model                    191796 non-null  object
 3   vehicle_type                     193568 non-null  object
 4   manufacturing_year               190171 non-null  float64
 5   battery_manufacturer             193812 non-null  object
 6   battery_chemistry                192786 non-null  object
 7   battery_capacity_kwh             193097 non-null  float64
 8   drive_type                       192732 non-null  object
 9   odometer_km                      191334 non-null  float64
 10  vehicle_age_years                192317 non-null  float64
 11  fleet_or_private                 191050 non-null  object
 12  battery_serial                   200000 non-null  object
 13  cycle_count                      192348 non-null  float64
 14  battery_health_percent           191018 non-null  float64
 15  state_of_charge                  190364 non-null  float64
 16  depth_of_discharge               191687 non-null  float64
 17  state_of_health                  190435 non-null  float64
 18  cell_voltage_avg                 190602 non-null  float64
 19  cell_voltage_std                 191437 non-null  float64
 20  pack_voltage                     193825 non-null  float64
 21  cell_temperature_avg             192317 non-null  float64
 22  cell_temperature_max             190550 non-null  float64
 23  internal_resistance              192025 non-null  float64
 24  charge_efficiency                190695 non-null  float64
 25  discharge_efficiency             193199 non-null  float64
 26  remaining_capacity               193852 non-null  float64
 27  capacity_loss_percent            190441 non-null  float64
 28  charging_cycles_last_month       192029 non-null  float64
 29  fast_charge_ratio                190121 non-null  float64
 30  slow_charge_ratio                190517 non-null  float64
 31  average_charge_power_kw          190950 non-null  float64
 32  average_charging_time            193851 non-null  float64
 33  overnight_charging_ratio         192601 non-null  float64
 34  home_charging_ratio              190195 non-null  float64
 35  charging_interruptions           190352 non-null  float64
 36  overcharge_events                192831 non-null  float64
 37  average_speed                    190151 non-null  float64
 38  average_trip_distance            192890 non-null  float64
 39  aggressive_acceleration_score    192730 non-null  float64
 40  hard_braking_score               190761 non-null  float64
 41  regenerative_braking_usage       190931 non-null  float64
 42  highway_driving_ratio            193517 non-null  float64
 43  city_driving_ratio               192755 non-null  float64
 44  daily_distance                   191432 non-null  float64
 45  average_ambient_temperature      190839 non-null  float64
 46  maximum_temperature              191781 non-null  float64
 47  minimum_temperature              193755 non-null  float64
 48  humidity                         191782 non-null  float64
 49  altitude                         191664 non-null  float64
 50  terrain_type                     192873 non-null  object
 51  dust_exposure                    193902 non-null  float64
 52  last_service_days                192663 non-null  float64
 53  cooling_system_health            190592 non-null  float64
 54  firmware_updates                 193783 non-null  float64
 55  previous_faults                  193717 non-null  float64
 56  maintenance_score                191554 non-null  float64
 57  thermal_runaway_risk             192794 non-null  float64
 58  voltage_imbalance                192765 non-null  float64
 59  temperature_variance             193645 non-null  float64
 60  sensor_fault_count               190326 non-null  float64
 61  BMS_warning_count                190948 non-null  float64
 62  abnormal_voltage_events          192400 non-null  float64
 63  battery_stress_index             192691 non-null  float64
 64  aging_score                      191635 non-null  float64
 65  thermal_health_score             193671 non-null  float64
 66  charging_quality_score           192814 non-null  float64
 67  driving_stress_score             193190 non-null  float64
 68  predicted_remaining_life_cycles  191026 non-null  float64
 69  battery_failure                  200000 non-null  int64
dtypes: float64(59), int64(1), object(10)
memory usage: 106.8+ MB

step 4: viewing dataset shape

In [8]:
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows : 200000
Columns : 70

step 5: checking duplicate rows

In [9]:
duplicates = df.duplicated().sum()
print(f"Duplicate Rows : {duplicates}")

Duplicate Rows : 0

In [10]:
missing_values =( df.isnull().sum().sort_values(ascending= False).to_frame(name = "missing values"))
missing_values["percentage"]=(missing_values["missing values"] / len(df)) * 100
missing_values.head(20)

                             missing values  percentage
fast_charge_ratio                      9879      4.9395
average_speed                          9849      4.9245
manufacturing_year                     9829      4.9145
home_charging_ratio                    9805      4.9025
sensor_fault_count                     9674      4.8370
charging_interruptions                 9648      4.8240
state_of_charge                        9636      4.8180
state_of_health                        9565      4.7825
capacity_loss_percent                  9559      4.7795
slow_charge_ratio                      9483      4.7415
cell_temperature_max                   9450      4.7250
cooling_system_health                  9408      4.7040
cell_voltage_avg                       9398      4.6990
charge_efficiency                      9305      4.6525
hard_braking_score                     9239      4.6195
average_ambient_temperature            9161      4.5805
regenerative_braking_usage             9069      4.5345
BMS_warning_count                      9052      4.5260
average_charge_power_kw                9050      4.5250
battery_health_percent                 8982      4.4910

step 6 : categorical summery

In [11]:
df.describe(include="object").T

                       count  unique           top    freq
vehicle_id            200000  200000      EV100000       1
vehicle_brand         193564      20         Tesla   21840
vehicle_model         191796      55       Model X    5527
vehicle_type          193568       6           SUV   58202
battery_manufacturer  193812       9          CATL   42675
battery_chemistry     192786       5           NMC  112993
drive_type            192732       3           FWD   86890
fleet_or_private      191050       2       Private  137463
battery_serial        200000  199775  BAT-31225896       2
terrain_type          192873       5          Flat   67488

step 7 : datatypes

In [13]:
df.dtypes.value_counts()

float64    59
object     10
int64       1
Name: count, dtype: int64

step 8: unique values

In [15]:
df.nunique().sort_values(ascending=False)

vehicle_id                         200000
battery_serial                     199775
odometer_km                        129048
pack_voltage                        34397
altitude                            16584
remaining_capacity                  11952
cell_voltage_avg                    11584
battery_capacity_kwh                10957
average_charge_power_kw             10643
state_of_charge                      9754
internal_resistance                  9350
cell_temperature_max                 8660
cell_temperature_avg                 7232
depth_of_discharge                   7186
state_of_health                      6170
capacity_loss_percent                6145
battery_health_percent               6142
voltage_imbalance                    6046
average_charging_time                5556
predicted_remaining_life_cycles      5169
cell_voltage_std                     4720
temperature_variance                 2690
discharge_efficiency                 2113
cycle_count                          1975
daily_distance                       1708
charge_efficiency                    1588
average_trip_distance                1187
last_service_days                    1028
vehicle_age_years                    1005
dust_exposure                        1001
charging_quality_score               1001
aging_score                          1001
driving_stress_score                 1001
battery_stress_index                 1001
home_charging_ratio                  1001
thermal_runaway_risk                 1000
slow_charge_ratio                     998
fast_charge_ratio                     997
aggressive_acceleration_score         975
city_driving_ratio                    956
humidity                              951
highway_driving_ratio                 950
average_speed                         940
maintenance_score                     921
hard_braking_score                    870
maximum_temperature                   869
overnight_charging_ratio              868
minimum_temperature                   862
regenerative_braking_usage            850
thermal_health_score                  794
cooling_system_health                 775
average_ambient_temperature           726
vehicle_model                          55
charging_cycles_last_month             40
firmware_updates                       30
vehicle_brand                          20
BMS_warning_count                      14
previous_faults                        12
sensor_fault_count                     11
charging_interruptions                 10
manufacturing_year                     10
battery_manufacturer                    9
overcharge_events                       8
abnormal_voltage_events                 8
vehicle_type                            6
battery_chemistry                       5
terrain_type                            5
drive_type                              3
fleet_or_private                        2
battery_failure                         2
dtype: int64

step 9: targate values

In [16]:
df["battery_failure"].value_counts(normalize=True)* 100

battery_failure
0    90.0395
1     9.9605
Name: proportion, dtype: float64

step 10: memory usage

In [17]:
memory = df.memory_usage(deep=True).sum() / (1024**2)

print(f"Dataset Memory : {memory:.2f} MB")

Dataset Memory : 196.22 MB