explore the file to view the dataset and checking the there noise or missing values

import libraries

In [59]:
import numpy as np 
import pandas as pd 
import warnings

warnings.filterwarnings("ignore")

loading the dataset

In [60]:
df = pd.read_csv(r"D:\machine learning\machine_learning\random_forest\social_media_predictiom\dataset\raw_dataset\archive\social_media_addiction_mental_wellbeing.csv")
df

,User_ID,Age,Gender,Occupation,Relationship_Status,Primary_Platform,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Late_Night_Usage,...,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score,Addiction_Level
0,USR00001,30,Male,Working Professional,In a Relationship,YouTube,2.9,4,3,No,...,1.7,6.5,8.5,5.3,3.7,3.8,5.8,3.1,7.3,Low
1,USR00002,19,Male,Student,Married,Instagram,4.8,1,0,NaN,...,7.0,7.5,7.8,5.5,4.0,1.8,0.9,3.3,4.1,Severe
2,USR00003,40,Male,Student,In a Relationship,YouTube,NaN,4,5,No,...,5.6,5.3,6.3,NaN,5.8,2.8,0.0,1.5,5.6,High
3,USR00004,37,Female,Student,Married,Facebook,7.7,2,3,Yes,...,5.6,1.4,3.9,6.1,5.5,3.6,1.0,3.9,4.3,Severe
4,USR00005,18,Non-binary,Student,In a Relationship,TikTok,4.6,3,0,No,...,4.0,NaN,5.7,5.0,3.8,3.2,0.6,1.0,6.6,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,USR01496,40,Male,Working Professional,In a Relationship,TikTok,2.7,2,4,No,...,3.3,7.4,8.5,6.7,4.5,7.6,2.3,2.3,6.5,High
1496,USR01497,23,Non-binary,Student,Married,YouTube,3.5,3,6,Yes,...,4.2,1.9,7.2,6.9,7.2,NaN,2.8,2.0,6.4,Moderate
1497,USR01498,39,Female,Student,Single,Instagram,5.3,2,3,Yes,...,0.4,2.4,5.1,NaN,6.4,7.8,2.6,4.8,4.7,Severe
1498,USR01499,26,Female,Freelancer,Single,Twitter/X,7.3,4,0,Yes,...,7.5,6.6,6.4,4.2,9.1,6.4,3.6,2.1,6.4,High
1499,USR01500,16,Female,Working Professional,In a Relationship,TikTok,0.7,3,2,No,...,5.9,8.5,5.3,7.2,3.4,2.3,3.9,3.1,6.1,Moderate

checking shape of the dataset

In [61]:
df.shape

(1500, 30)

In [75]:
df.isnull().sum()

User_ID                          0
Age                              0
Gender                          53
Occupation                      45
Relationship_Status             51
Primary_Platform                53
Daily_Usage_Hours               56
Platforms_Used_Count             0
Posts_Per_Week                   0
Late_Night_Usage                50
First_Check_Morning              0
Notifications_Per_Day            0
FOMO_Score                      55
Social_Comparison_Score         51
Validation_Seeking_Score        58
Scroll_Without_Purpose           0
Tried_To_Cut_Back               41
Failed_To_Cut_Back              43
Anxiety_Score                   48
Depression_Score                55
Loneliness_Score                55
Self_Esteem_Score               69
Sleep_Quality_Score             68
Sleep_Hours                     62
Productivity_Loss_Score         51
Offline_Relationship_Quality    70
Physical_Activity_Hrs_Week      51
Screen_Free_Time_Hrs            60
Mental_Wellbeing_Score           0
Addiction_Level                  0
dtype: int64

In [63]:
df.duplicated().sum()

np.int64(0)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   User_ID                       1500 non-null   object
 1   Age                           1500 non-null   int64
 2   Gender                        1447 non-null   object
 3   Occupation                    1455 non-null   object
 4   Relationship_Status           1449 non-null   object
 5   Primary_Platform              1447 non-null   object
 6   Daily_Usage_Hours             1444 non-null   float64
 7   Platforms_Used_Count          1500 non-null   int64
 8   Posts_Per_Week                1500 non-null   int64
 9   Late_Night_Usage              1450 non-null   object
 10  First_Check_Morning           1500 non-null   object
 11  Notifications_Per_Day         1500 non-null   int64
 12  FOMO_Score                    1445 non-null   float64
 13  Social_Comparison_Score       1449 non-null   float64
 14  Validation_Seeking_Score      1442 non-null   float64
 15  Scroll_Without_Purpose        1500 non-null   float64
 16  Tried_To_Cut_Back             1459 non-null   object
 17  Failed_To_Cut_Back            1457 non-null   object
 18  Anxiety_Score                 1452 non-null   float64
 19  Depression_Score              1445 non-null   float64
 20  Loneliness_Score              1445 non-null   float64
 21  Self_Esteem_Score             1431 non-null   float64
 22  Sleep_Quality_Score           1432 non-null   float64
 23  Sleep_Hours                   1438 non-null   float64
 24  Productivity_Loss_Score       1449 non-null   float64
 25  Offline_Relationship_Quality  1430 non-null   float64
 26  Physical_Activity_Hrs_Week    1449 non-null   float64
 27  Screen_Free_Time_Hrs          1440 non-null   float64
 28  Mental_Wellbeing_Score        1500 non-null   float64
 29  Addiction_Level               1500 non-null   object
dtypes: float64(16), int64(4), object(10)
memory usage: 351.7+ KB

In [65]:
df_gender = df[["Age"]].max().max()
print(df_gender)

44

In [79]:
df_mean = df["Age"].mean()
print(df_mean)

29.372

In [80]:
df["Age"].fillna(df_mean, inplace = True)

In [81]:
df.describe()

,Age,Daily_Usage_Hours,Platforms_Used_Count,Posts_Per_Week,Notifications_Per_Day,FOMO_Score,Social_Comparison_Score,Validation_Seeking_Score,Scroll_Without_Purpose,Anxiety_Score,Depression_Score,Loneliness_Score,Self_Esteem_Score,Sleep_Quality_Score,Sleep_Hours,Productivity_Loss_Score,Offline_Relationship_Quality,Physical_Activity_Hrs_Week,Screen_Free_Time_Hrs,Mental_Wellbeing_Score
count,1500.000000,1444.000000,1500.000000,1500.000000,1500.000000,1445.000000,1449.000000,1442.000000,1500.000000,1452.000000,1445.000000,1445.000000,1431.000000,1432.000000,1438.000000,1449.000000,1430.000000,1449.000000,1440.000000,1500.000000
mean,29.372000,4.521399,3.236000,3.936000,60.244667,5.445882,5.495514,5.013107,5.449867,5.110537,4.562630,4.484429,5.519846,5.508659,6.557580,5.026570,5.482797,3.016494,3.025903,6.429733
std,8.550459,2.108319,1.682714,1.948273,33.150688,2.183914,2.041919,2.112417,2.083848,2.157587,2.199201,1.997623,1.993134,1.997842,1.380144,2.114049,2.045514,1.715963,1.691351,1.299288
min,15.000000,0.500000,1.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.500000
25%,22.000000,3.100000,2.000000,3.000000,36.000000,4.000000,4.100000,3.600000,4.000000,3.700000,3.100000,3.100000,4.200000,4.100000,5.600000,3.600000,4.100000,1.800000,1.800000,5.500000
50%,29.000000,4.400000,3.000000,4.000000,59.000000,5.500000,5.500000,5.000000,5.500000,5.100000,4.500000,4.500000,5.600000,5.500000,6.600000,5.000000,5.400000,3.000000,3.000000,6.400000
75%,37.000000,5.900000,4.000000,5.000000,81.250000,7.000000,6.900000,6.500000,6.900000,6.600000,6.000000,5.900000,6.900000,6.900000,7.500000,6.400000,7.000000,4.200000,4.200000,7.300000
max,44.000000,12.000000,8.000000,12.000000,165.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.900000,10.300000,10.000000

In [82]:
df.dtypes

User_ID                          object
Age                               int64
Gender                           object
Occupation                       object
Relationship_Status              object
Primary_Platform                 object
Daily_Usage_Hours               float64
Platforms_Used_Count              int64
Posts_Per_Week                    int64
Late_Night_Usage                 object
First_Check_Morning              object
Notifications_Per_Day             int64
FOMO_Score                      float64
Social_Comparison_Score         float64
Validation_Seeking_Score        float64
Scroll_Without_Purpose          float64
Tried_To_Cut_Back                object
Failed_To_Cut_Back               object
Anxiety_Score                   float64
Depression_Score                float64
Loneliness_Score                float64
Self_Esteem_Score               float64
Sleep_Quality_Score             float64
Sleep_Hours                     float64
Productivity_Loss_Score         float64
Offline_Relationship_Quality    float64
Physical_Activity_Hrs_Week      float64
Screen_Free_Time_Hrs            float64
Mental_Wellbeing_Score          float64
Addiction_Level                  object
dtype: object

In [83]:
df_fomo = df["FOMO_Score"].mean(0)
print(df_fomo)

5.445882352941176

In [84]:
df["FOMO_Score"].fillna(df_fomo, inplace=True)

In [164]:
df.isnull().sum()

User_ID                          0
Age                              0
Gender                           0
Occupation                       0
Relationship_Status              0
Primary_Platform                 0
Daily_Usage_Hours                0
Platforms_Used_Count             0
Posts_Per_Week                   0
Late_Night_Usage                 0
First_Check_Morning              0
Notifications_Per_Day            0
FOMO_Score                       0
Social_Comparison_Score          0
Validation_Seeking_Score         0
Scroll_Without_Purpose           0
Tried_To_Cut_Back                0
Failed_To_Cut_Back               0
Anxiety_Score                    0
Depression_Score                 0
Loneliness_Score                55
Self_Esteem_Score               69
Sleep_Quality_Score             68
Sleep_Hours                     62
Productivity_Loss_Score         51
Offline_Relationship_Quality    70
Physical_Activity_Hrs_Week      51
Screen_Free_Time_Hrs            60
Mental_Wellbeing_Score           0
Addiction_Level                  0
dtype: int64

In [99]:
df_usage = df["Daily_Usage_Hours"].median()
print(df_usage)

4.4

In [100]:
df['Daily_Usage_Hours'].fillna(df_usage , inplace=True)

In [104]:
df_gen = df["Gender"].mode()
print(df_gen)

0    Male
Name: Gender, dtype: object

In [107]:
df['Gender'].fillna(df_gen[0] , inplace=True)

In [112]:
df_rel = df["Relationship_Status"].mode()
print(df_rel)

0    Single
Name: Relationship_Status, dtype: object

In [113]:
df["Relationship_Status"].fillna(df_rel[0] , inplace = True)

In [116]:
df_occ = df["Occupation"].mode()
print(df_occ)

0    Student
Name: Occupation, dtype: object

In [117]:
df["Occupation"].fillna(df_occ[0] , inplace=True)

In [120]:
df_plat = df["Primary_Platform"].mode()
print(df_plat)

0    Instagram
Name: Primary_Platform, dtype: object

In [121]:
df["Primary_Platform"].fillna(df_plat[0] , inplace = True)

In [124]:
df_last =  df["Late_Night_Usage"].mode()
print(df_last)

0    Yes
Name: Late_Night_Usage, dtype: object

In [127]:
df["Late_Night_Usage"].fillna(df_last[0] , inplace = True)

In [133]:
df_social = df["Social_Comparison_Score"].mean()
print(df_social)

5.495514147688061

In [134]:
df["Social_Comparison_Score"].fillna(df_social , inplace = True)

In [140]:
df_valid = df["Validation_Seeking_Score"].median()
print(df_valid)

5.0

In [141]:
df["Validation_Seeking_Score"].fillna(df_valid , inplace=True)

In [144]:
df_tied = df["Tried_To_Cut_Back"].mode()
print(df_tied)

0    Yes
Name: Tried_To_Cut_Back, dtype: object

In [145]:
df["Tried_To_Cut_Back"].fillna(df_tied[0] , inplace=True)

In [148]:
df_failed = df["Failed_To_Cut_Back"].mode()
print(df_failed)

0    No
Name: Failed_To_Cut_Back, dtype: object

In [149]:
df["Failed_To_Cut_Back"].fillna(df_failed[0] , inplace=True)

In [155]:
df_anx = df["Anxiety_Score"].median()
print(df_anx)

5.1

In [156]:
df["Anxiety_Score"].fillna(df_anx , inplace = True)

In [162]:
df_depre = df["Depression_Score"].median()
print(df_depre)

4.5

In [163]:
df["Depression_Score"].fillna(df_depre , inplace=True)